version: "4"

services:
  database :
    image: postgres:latest
    environment :
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
